# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title gibbs_cpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbs_cpp(5,2,3) 
#'  par(mfrow=c(2,1));
#'  plot(rnC[,1],type='l') 
#'  plot(rnC[,2],type='l')
#' } 
#' @export
NULL

gibbs_cpp <- function(n, a, b) {
    .Call('_StatComp21035_gibbs_cpp', PACKAGE = 'StatComp21035', n, a, b)
}

